---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.132140'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LaTeX-Driver
no_index:
  directory:
    - t
    - inc
requires:
  Class::Accessor: 0
  Cwd: 0
  Exception::Class: 0
  File::Slurp: 0
  File::Spec: 0
  IO::File: 0
  IPC::ShellCmd: 0
  Readonly: 0
version: 0.2002
